// Hero background texture (DECISIONS D6-A): static curated list of real lines
// from Ishan's changelogs/READMEs (handoff/research/). Rendered at 4–6% opacity.
// TODO(M4): enrich from actual `git log` once repos are cloned locally.
export const commitTexture = [
  "fix: docker container restart loop — restart policy set to \"no\"",
  "feat: intelligent rate limiting — default delay 2s→5s, 12 req/min",
  "fix: chromedriver version mismatch — use system driver from apt",
  "feat: per-minute request counter with exponential backoff on 429s",
  "docs: model corrected — gemini-2.5-flash-lite, not pro",
  "feat: section-count optimization, 9–15 by project size",
  "feat: max 8 screenshots with priority selection, max 3 diagrams",
  "feat: auto-numbered TOC with hierarchical section listing",
  "fix: mermaid prompts capped — 5-7 nodes max, <500 chars",
  "feat: redis distributed lock + SELECT FOR UPDATE + version check",
  "feat: immutable JSONB audit log — field diffs, actor id, client ip",
  "feat: sliding-window lua rate limiting, 100 req/min per ip",
  "feat: batch creation of 50 events in one atomic round-trip",
  "feat: jwt hs256 rbac — user reads, admin writes",
  "chore: multi-stage docker build, ~15MB final image",
  "feat: versioned sql migrations auto-applied at startup",
  "docs: browser deps clarified — selenium screenshots, puppeteer only in mmdc",
  "feat: cancellation restores ticket inventory",
  "feat: zerolog structured json — pretty in dev, compact in prod",
  "fix: api rate limit violations during large doc generation",
  "feat: hyperlink support — automatic url detection in generated docs",
  "feat: ast-based retrieval over claude skill library",
  "feat: human-gated approval loop for skill distillation",
  "feat: contributors metadata via environment variables",
  "fix: screenshot failures in containerized environment",
  "docs: readme rewrite that corrected its own claims",
  "feat: content generation optimization — reduce calls, don't pace them",
  "feat: intersectionobserver nav + counters, print stylesheet",
  "chore: zero dependencies, design tokens in :root",
  "feat: byok model — no server-side key custody",
] as const;
